{
  "formatVersion": "1.1",
  "component": {
    "group": "vazkii.patchouli",
    "module": "Patchouli",
    "version": "1.17.1-57-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Patchouli-1.17.1-57-SNAPSHOT.jar",
          "url": "Patchouli-1.17.1-57-SNAPSHOT.jar",
          "size": 627147,
          "sha512": "87e9a68f10288fa7950df010e31edcd94d7c5e22070799f5e55c17dec5048cfc03e0d1a0d88578c187d461eadb373375b9f4c1ee35281ed54ccc6ba6d567c5b4",
          "sha256": "2aefff9e68d93f53bb9a77041c528be40cc8d220129e88d44d44f24dcacebfbc",
          "sha1": "d465e31dd3a9ec9d06d17374a344be18b9f2da7d",
          "md5": "a87000f544569e62a81e2244550844c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.17.1-37.0.90_mapped_official_1.17.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.17.1",
          "version": {
            "strictly": "8.0.0.16_mapped_official_1.17.1",
            "requires": "8.0.0.16_mapped_official_1.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "Patchouli-1.17.1-57-SNAPSHOT.jar",
          "url": "Patchouli-1.17.1-57-SNAPSHOT.jar",
          "size": 627147,
          "sha512": "87e9a68f10288fa7950df010e31edcd94d7c5e22070799f5e55c17dec5048cfc03e0d1a0d88578c187d461eadb373375b9f4c1ee35281ed54ccc6ba6d567c5b4",
          "sha256": "2aefff9e68d93f53bb9a77041c528be40cc8d220129e88d44d44f24dcacebfbc",
          "sha1": "d465e31dd3a9ec9d06d17374a344be18b9f2da7d",
          "md5": "a87000f544569e62a81e2244550844c6"
        }
      ]
    }
  ]
}
